# Generated by Django 4.2.1 on 2024-03-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Номер вопроса')),
                ('date', models.DateTimeField(verbose_name='Время создания вопроса')),
                ('ques', models.CharField(max_length=250, verbose_name='Текст вопроса')),
            ],
        ),
    ]
