# Generated by Django 4.2.1 on 2024-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(verbose_name='Время создания вопроса:'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ques',
            field=models.CharField(max_length=250, verbose_name='Текст вопроса:'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Номер вопроса:'),
        ),
    ]
